fusion:
  brokers:
    - channel: NA
      hostUrl: ${MQ_URL}
      brokerId: fusionBroker
      jmsProvider: ACTIVEMQ
      queueManagerName: NA
      sendSessionCacheSize: 10
      userName: admin
      amqpRedeliveryPolicy:
        backOffMultiplier: 1.0
        maxDeliveries: 3
        queueNameRegex: "*"
        redeliveryDelay: 3000
        useExponentialBackOff: true
        maxDeliveryDelay: 3600000
        initialRedeliveryDelay: 0

  usecases:
    - name: RestRetryPickBegin
      version: 1
      activeConfig: adapterConfig
      configs:
        - name: adapterConfig
          adapters:
            - adapterType: inbound
              brokerId: fusionBroker
              queueName: US.FUSION.ALPHA.RETRY.IN
              readConcurrency: 1-1
              messageType: JSON
            - adapterType: outbound
              trasnportType: JMS
              usecaseResult: FAILURE
              brokerId: fusionBroker
              queueName: US.FUSION.ALPHA.RETRY.IN.ERROR.QUEUE
    - name: RestRetryPickEnd
      version: 1
      activeConfig: adapterConfig
      configs:
        - name: adapterConfig
          adapters:
            - adapterType: inbound
              brokerId: fusionBroker
              queueName: US.FUSION.ALPHA.RETRY.IN
              readConcurrency: 1-1
              messageType: JSON
            - adapterType: outbound
              trasnportType: JMS
              usecaseResult: FAILURE
              brokerId: fusionBroker
              queueName: US.FUSION.ALPHA.RETRY.IN.ERROR.QUEUE
usecase: ${USECASE}
timeOutInSeconds: ${TIME_OUT_IN_SECONDS}