fusion:
  brokers:
    - channel: NA
      hostUrl: 'tcp://127.0.0.1:61616'
      brokerId: fusionBroker
      jmsProvider: ACTIVEMQ
      queueManagerName: NA
      sendSessionCacheSize: 10
      userName: admin
      amqpRedeliveryPolicy:
         backOffMultiplier: 1.0
         maxDeliveries: 3
         queueNameRegex: "*"
         redeliveryDelay: 3000
         useExponentialBackOff: true
         maxDeliveryDelay: 3600000
         initialRedeliveryDelay: 0
spring:
  datasource:
    platform: mariadb
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb:failover://localhost:3306/fusion?autoReconnect=true
    username: fusion
    password: fusion
    timeBetweenEvictionRunsMillis: 1000
    testWhileIdle: true
  liquibase:
    enabled: false
  hikari:
    connectionTimeout: 30000
    idleTimeout: 30000
    maxLifetime: 2000000
    maximumPoolSize: 20
    minimumIdle: 5
    poolName: SpringBootJPAHikariCP
  jpa:
    ddl-auto: ''
    show-sql: true