fusion:
  brokers:
    - channel: NA
      hostUrl: 'tcp://127.0.0.1:61616'
      brokerId: fusionBroker
      jmsProvider: ACTIVEMQ
      queueManagerName: NA
      sendSessionCacheSize: 10
      userName: admin
      amqpRedeliveryPolicy:
         backOffMultiplier: 1.0
         maxDeliveries: 3
         queueNameRegex: "*"
         redeliveryDelay: 3000
         useExponentialBackOff: true
         maxDeliveryDelay: 3600000
         initialRedeliveryDelay: 0
         
  usecases:
    - name: RestRetryOrderCreate
      version: 1
      activeConfig: adapterConfig
      configs:
        - name: adapterConfig
          adapters:
            - adapterType: inbound
              brokerId: fusionBroker
              queueName: ORDER.CREATE.RETRY.IN
              messageType: JSON