# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  marvel: scoperetail/marvel@2.6.0

workflows:
  build-and-test:
    jobs:
      - marvel/maven-deploy:
          context:
            - OSSRH
            - SLACK
          filters:
            branches:
              ignore:
                - master
                - /HOTFIX-.*/
      - marvel/sonar-scan:
          context:
            - OSSRH
            - SLACK
          filters:
            branches:
              ignore:
                - master
                - /HOTFIX-.*/
      - marvel/maven-release-docker:
          context:
            - OSSRH
            - DOCKER_SCOPERETAIL
            - SLACK
            - ARTIFACTORY
          filters:
            branches:
              only:
                - master
                - /HOTFIX-.*/
